version: '3.8'

services:
  app:
    platform: 'linux/amd64'
    build:
      context: ./php
    container_name: php-app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    # depends_on:
    #   - mysql
    networks:
      - laravel-network

  web:
    platform: 'linux/amd64'
    build:
      context: ./nginx
    container_name: web-server
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel-network

  # mysql:
  #   platform: 'linux/amd64'
  #   image: mysql:8.0
  #   container_name: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - laravel-network

  # node:
  #   platform: 'linux/amd64'
  #   image: node:20
  #   container_name: laravel-node
  #   working_dir: /var/www/html
  #   volumes:
  #     - ./src:/var/www/html
  #   command: sh -c "npm install && npm run dev"
  #   ports:
  #     - "5173:5173" # Viteのデフォルトポート
  #   networks:
  #     - laravel-network

volumes:
  mysql_data:

networks:
  laravel-network: