name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Docker Compose をインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: AWS にログイン
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ECR にログイン
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker イメージをビルド
        run: |
          docker-compose build

      - name: デバッグ: `docker-compose images`
        run: |
          set -x  # デバッグモード有効化
          docker-compose images  # どのサービスがあるか確認

      - name: イメージを ECR にタグ付け & プッシュ
        run: |
          set -x  # デバッグモード有効化
          NGX_IMAGE=$(docker-compose images -q nginx)
          PHP_IMAGE=$(docker-compose images -q php)

          echo "NGX_IMAGE=$NGX_IMAGE"
          echo "PHP_IMAGE=$PHP_IMAGE"

          docker tag $NGX_IMAGE ${{ secrets.ECR_REGISTRY }}/my-nginx-repo:latest
          docker tag $PHP_IMAGE ${{ secrets.ECR_REGISTRY }}/my-php-repo:latest

          docker push ${{ secrets.ECR_REGISTRY }}/my-nginx-repo:latest
          docker push ${{ secrets.ECR_REGISTRY }}/my-php-repo:latest
